#
#     DOCKER COMPOSE FILE
#     YAML file defining services, networks, and volumes for the Variant Hunter Docker application.
#
#     Run the docker with the following commands:
#     docker pull gecopolimi/varianthunter
#     {parameters_list} docker-compose up
#
#     More details at http://cerilab.deib.polimi.it/variant_hunter/about#docker
#

version: "3"
services:
  app:
    image: gecopolimi/varianthunter
    command:
      bash -c "
        [ '${REGENERATE:-false}' == 'false' ] 
        && { python -u ./backend/app.py -fp /backend/app/dataset/metadata.tsv -loc '${LOCATIONS:-all}' -ft ${FILE_TYPE:-gisaid} -sd ${START_DATE:-beginning} -ed ${END_DATE:-end};}
        || { python -u ./backend/app.py -fp /backend/app/dataset/metadata.tsv -loc '${LOCATIONS:-all}' -ft ${FILE_TYPE:-gisaid} -sd ${START_DATE:-beginning} -ed ${END_DATE:-end} -r;}
      "
    ports:
      - "${PORT:-5000}:5000"
    volumes:
      - ${FILE_PATH:-./}:/backend/app/dataset/metadata.tsv  # default value never used
      - ${DB_PATH:-./}:/backend/app/data_e/  # default value never used
    environment:
      - PORT=${PORT:-5000}
      - DB_PATH=${DB_PATH:-unset}
