version: "3"
services:
  app:
    image: gecopolimi/varianthunter
    command: python -u ./backend/app.py -fp /backend/app/database/metadata.tsv -loc ${LOCATIONS:-all} -ft ${FILE_TYPE:-gisaid} -sd ${START_DATE:-beginning} -ed ${END_DATE:-end}
    ports:
      - "${PORT:-5000}:5000"
    volumes:
      - ${FILE_PATH}:/backend/app/database/metadata.tsv