version: "3"
services:
  app:
    image: gecopolimi/varianthunter
    command:
      bash -c "
        [ '${RELOAD:-false}' == 'false' ] 
        && { python -u ./backend/app.py -fp /backend/app/database/metadata.tsv -loc '${LOCATIONS:-all}' -ft ${FILE_TYPE:-gisaid} -sd ${START_DATE:-beginning} -ed ${END_DATE:-end};}
        || { python -u ./backend/app.py -fp /backend/app/database/metadata.tsv -loc '${LOCATIONS:-all}' -ft ${FILE_TYPE:-gisaid} -sd ${START_DATE:-beginning} -ed ${END_DATE:-end} -r;}
      "
    ports:
      - "${PORT:-5000}:5000"
    volumes:
      - ${FILE_PATH}:/backend/app/database/metadata.tsv
      - ${DB_PATH:-./}:/backend/app/db/  # if not specified, it is not used
    environment:
      - PORT=${PORT:-5000}
      - DB_PATH=${DB_PATH:-unset}