services:
  app:
    build: .
    image: gecopolimi/varianthunter
    command: python -u ./backend/app.py /backend/app/database/${FILE_NAME} '${LOCATION}'
    ports:
      - "5000:5000"
    volumes:
      - ${FILE_PATH}:/backend/app/database/
    environment:
      - FILE_PATH=${FILE_PATH}
      - FILE_NAME=${FILE_NAME}
      - LOCATION=${LOCATION}